'use client';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, BookOpen, Check, Code2, GitFork, Mail, Moon, Sun, Trophy } from 'lucide-react';
import Particles from './particles';
import { education, experience, research, projects, awards, skills } from './content';
const nav = [['hero','Home'],['education','Education'],['experience','Experience'],['research','Research'],['projects','Projects'],['honors','Honors'],['skills','Skills']];
export default function Home() {
 const [lang,setLang]=useState(0),[theme,setTheme]=useState('dark'),[active,setActive]=useState('hero'),[copied,setCopied]=useState(false);
 const t=(zh:string,en:string)=>lang===0?zh:en;
 useEffect(()=>{try {const saved=localStorage.getItem('cumberbear-theme');if(saved==='light'){setTheme('light');document.documentElement.dataset.theme='light';}const l=localStorage.getItem('cumberbear-lang');if(l==='1')setLang(1);} catch {}},[]);
 useEffect(()=>{document.documentElement.lang=lang?'en':'zh-CN';},[lang]);
 useEffect(()=>{const obs=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id);},{rootMargin:'-12% 0px -65% 0px'});document.querySelectorAll('section[id]').forEach(el=>obs.observe(el));return()=>obs.disconnect();},[]);
 function toggleTheme(){const v=theme==='dark'?'light':'dark';setTheme(v);document.documentElement.dataset.theme=v;try{localStorage.setItem('cumberbear-theme',v);}catch{}}
 function toggleLang(){setLang(1-lang);try{localStorage.setItem('cumberbear-lang',String(1-lang));}catch{}}
 async function copyEmail(){try {await navigator.clipboard.writeText('whubear@whu.edu.cn');setCopied(true);setTimeout(()=>setCopied(false),2200);}catch{location.href='mailto:whubear@whu.edu.cn';}}
 return <>
 <a className="skip" href="#education">{t('跳至主要内容','Skip to content')}</a>
 <header><nav aria-label={t('主导航','Main navigation')}><div className="nav-links">{nav.map(([id,label])=><a key={id} href={`#${id}`} className={active===id?'active':''} aria-current={active===id?'location':undefined}>{label}</a>)}</div><div className="nav-tools"><button onClick={toggleLang} aria-label={t('Switch to English','切换到中文')}>{lang?'中':'EN'}</button><button onClick={toggleTheme} aria-label={theme==='dark'?t('切换到浅色模式','Switch to light mode'):t('切换到深色模式','Switch to dark mode')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button></div></nav></header>
 <main>
 <section id="hero" className="hero"><Particles/><div className="hero-card"><div className="profile"><div className="avatar" aria-label="CumberBear"><img src="/avatar.png" alt="赵子博 CumberBear" width={160} height={160} fetchPriority="high"/><i/></div><div className="intro"><h1>{t('赵子博','Zibo Zhao')} <span>(CumberBear)</span></h1><p className="roles">{t('Agentic / LLM 算法工程师','Agentic / LLM AI Engineer')}<b>/</b>{t('自进化系统构建者','Self-Evolving Systems Builder')}</p><p className="tagline">Building agents that learn to build better agents.</p><div className="socials"><a href="https://github.com/EvoMap/evolver" target="_blank" rel="noreferrer" aria-label="EvoMap Evolver on GitHub" title="EvoMap / Evolver"><GitFork size={17}/></a><a href="#research" aria-label={t('研究论文','Research papers')} title={t('研究论文','Research papers')}><BookOpen size={17}/></a><a href="mailto:whubear@whu.edu.cn" aria-label={t('发送邮件','Send email')} title="whubear@whu.edu.cn"><Mail size={17}/></a></div></div></div><div className="hero-note"><p>AgentX Core Contributor <span>·</span> {t('Agentic / LLM 算法工程师','Agentic / LLM AI Engineer')}</p><p>{t('专注 Agent 自进化、长程工具规划与多模态生成，让真实世界的反馈成为下一次进化的起点。','Working on agent self-evolution, long-horizon tool planning and multimodal generation. Turning real-world feedback into the next iteration.')}</p></div></div><a href="#education" className="scroll-hint" aria-label={t('向下探索','Explore below')}><span>SCROLL TO EXPLORE</span><ArrowDown size={17}/></a></section>
 <div className="intro-strip"><span className="status-dot"/>{t('武汉大学 · 数据科学硕士在读','Wuhan University · M.S. in Data Science')}<span className="strip-separator">/</span><span>Agentic AI & Recursive Self-Improvement</span></div>
 <section id="education" className="section"><div className="container"><SectionTitle en="Education" title={t('教育背景','Academic background')}/><div className="stack">{education.map(e=><article className="module row" key={e.mark}><div className="mark org-logo"><img src={e.logo} alt={e.title[lang]} width={40} height={40} loading="lazy"/></div><div className="row-body"><div className="heading-row"><h3>{e.title[lang]}</h3><span className="date">{e.date}</span></div><p>{e.role[lang]}</p></div></article>)}</div></div></section>
 <section id="experience" className="section"><div className="container"><SectionTitle en="Experience" title={t('工作与实习','Work & internships')}/><div className="stack">{experience.map((e,i)=><article className="module row" key={i}><div className="mark org-logo"><img src={e.logo} alt={e.title[lang]} width={40} height={40} loading="lazy"/></div><div className="row-body"><div className="heading-row"><h3>{e.title[lang]}</h3><span className="date">{e.date}</span></div><p className="role">{e.role[lang]}</p><ul className="details">{e.items.map((item,j)=><li key={j}><Emphasis text={item[lang]}/></li>)}</ul></div></article>)}</div></div></section>
 <section id="research" className="section"><div className="container"><SectionTitle en="Research" title={t('研究与论文','Research & publications')}/><div className="stack research-list">{research.map((r,i)=><article className="module paper" key={i}><div className="paper-icon"><BookOpen size={20}/></div><div className="row-body"><h3>{r.url?<a href={r.url} target="_blank" rel="noreferrer">{lang&&r.titleEn?r.titleEn:r.title}<ArrowUpRight size={16}/></a>:lang&&r.titleEn?r.titleEn:r.title}</h3><span className="paper-tag">{r.tag[lang]}</span><p>{r.body[lang]}</p></div></article>)}</div></div></section>
 <section id="projects" className="section"><div className="container"><SectionTitle en="Projects" title={t('构建与探索','Selected projects')}/><div className="stack project-list">{projects.map(p=><article className="module row project-entry" key={p.title}><div className="mark"><Code2 size={19}/></div><div className="row-body"><div className="heading-row"><h3>{p.href?<a href={p.href} target="_blank" rel="noreferrer">{p.title}<ArrowUpRight size={15}/></a>:p.title}</h3><span className="date">{p.tag}</span></div><p className="role">{p.sub[lang]}</p><ul className="details">{p.body[lang].split(lang===0?'。':'. ').filter(Boolean).map((line,i)=><li key={i}><Emphasis text={line+(lang===0?'。':'')}/></li>)}<li><strong>{t('成果与产出','Results & contributions')}：</strong>{p.stats.map((stat,i)=><span key={stat}>{i?' · ':''}<strong>{stat}</strong></span>)}</li></ul></div></article>)}</div><p className="source-note">{t('项目数据与研究状态依据 2026.09.18 简历；团队整体成果与个人贡献按原口径区分。','Project metrics and research status are based on the September 18, 2026 résumé; team outcomes and individual contributions retain their original scope.')}</p></div></section>
 <section id="honors" className="section"><div className="container"><SectionTitle en="Honors" title={t('荣誉与认可','Honors & recognition')}/><div className="stack">{awards.map((a,i)=><article className="module award" key={i}><Trophy size={19}/><h3>{a[lang]}</h3><span>{a[2]}</span></article>)}</div></div></section>
 <section id="skills" className="section"><div className="container"><SectionTitle en="Skills" title={t('技术栈','Tools & technologies')}/><div className="skills">{skills.map(([label,...items])=><div className="skill-row" key={label}><h3>{label}</h3><div>{items.map(item=><span className="skill" key={item}>{item}</span>)}</div></div>)}</div></div></section>
 <section className="contact"><div className="container"><span className="eyebrow">Get in touch</span><h2>{t('一起探索 Agent 的下一步。','Let’s explore what agents can become.')}</h2><a className="email" href="mailto:whubear@whu.edu.cn">whubear@whu.edu.cn<ArrowUpRight size={20}/></a><button className="copy" onClick={copyEmail}>{copied?<Check size={14}/>:null}{copied?t('已复制','Copied'):t('复制邮箱','Copy email')}</button><span role="status" className="sr-only">{copied?t('邮箱已复制','Email copied'):''}</span></div></section>
 </main><footer className="footer"><span>© {new Date().getFullYear()} CumberBear</span><span>Always learning. Always evolving.</span><a href="#hero" aria-label={t('回到顶部','Back to top')}><ArrowUp size={16}/></a></footer>
 </>;
}
function SectionTitle({en,title}:{en:string;title:string}) {return <div className="section-title"><p className="eyebrow">{en}</p><h2>{title}</h2></div>;}

const highlights = ['面向工业推荐研发的 RSI-Agent 框架','SGPO 自进化体系','RSI 驱动剧游架构演进','RSI 持续进化','RSI-Agent framework for industrial recommendation','SGPO self-evolution','RSI-driven game-agent evolution','Continuous RSI','Harness Evolution','Co-Agent','AutoResearch','长程 Agentic RL','long-horizon Agentic RL','OrgGene / OrgCapsule','TeamGraph','374 个 Idea','10 个可全量实验','3.7 倍','3.7×','日均 DAU 破万','纯新用户 3 万','7 个互动剧本','7 组互动影游','67.3%','92.3%','8 大行业模板','0.68','−9.47%'];
function Emphasis({text}:{text:string}) {
 const match=highlights.filter(word=>text.includes(word)).sort((a,b)=>b.length-a.length);
 if(!match.length)return <>{text}</>;
 const escaped=match.map(word=>word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
 const pattern=new RegExp('('+escaped.join('|')+')','g');
 return <>{text.split(pattern).map((part,i)=>match.includes(part)?<strong key={i}>{part}</strong>:part)}</>;
}
